feat: add gallery section for desktop
pankiale/lyubimovka pull request #20
Opened 2022-06-07 15:34 UTC by nadyaiva

Добавила секцию фотографий для десктопной версии. Можно проверять)

2022-06-07 15:55 UTC, Serebrennikovki commented on src/index.html
> +					<button>БИЛЕТЫ</button>
не указан атрибут у кнокпи

2022-06-07 16:25 UTC, pankiale requested changes

2022-06-07 16:25 UTC, pankiale commented on src/blocks/photo/photo.css
> +	margin: 0 auto;
magin auto а в верстке заголовок смещен влево. вохможно лучше указать margin left в % или использовать иной способ позиционирования заголовка?

2022-06-07 16:31 UTC, Serebrennikovki commented on src/blocks/photo/photo.css
> +	margin: 0 auto;
margin неверно задан. он должен быть смещен левее по макету.

2022-06-07 16:31 UTC, Serebrennikovki commented on src/blocks/photo-gallery/photo-gallery.css
> +	height: 100%;
наверное стоит добавить правило object-fit, то есть, что делать картинке если она меньше заданного места в таблице

2022-06-07 16:49 UTC, nadyaiva commented on src/blocks/photo/photo.css
> +	margin: 0 auto;
По макету заголовок также смещен влево, поэтому я задала блоку ширину. Можно и другой способ использовать, если c этим проблемы. Можешь пояснить, пожалуйста, в чем проблема.

2022-06-07 18:20 UTC, nadyaiva commented on src/blocks/photo-gallery/photo-gallery.css
> +	height: 100%;
Спасибо! Добавила object-fit: cover

2022-06-07 18:27 UTC, nadyaiva commented on src/blocks/photo/photo.css
> +	margin: 0 auto;
Спасибо! Задала max-with с помощью calc

2022-06-07 18:28 UTC, nadyaiva commented on src/blocks/photo/photo.css
> +	margin: 0 auto;
Поняла. Исправила

2022-06-07 19:39 UTC, s-gusterev commented on src/index.html
> +				<h2 class="section__title">
Сейчас заголовок  - это элемент. А элемент по бэму не может быть отдельно вне блока. Лучше сделать заголовок блоком, а внешнюю геометрию добавить элементу. `<h2 class="section-title photo__title">`.

2022-06-07 19:53 UTC, nadyaiva commented on src/index.html
> +				<h2 class="section__title">
Ты прав, что нельзя задавать внешнюю геометрию блоку. Но не хотелось бы использовать два селектора, там где можно обойтись одним. Все заголовки имеют одинаковый отступ. Не уверена, но может использовать модификатор? Например title_section?

2022-06-07 20:20 UTC, s-gusterev commented on src/index.html
> +				<h2 class="section__title">
c модификатором только так
`title title_section`
Все равно получается два селектора. В твоей секции отступ 40, а в секции отзывы зрителей 60

2022-06-07 21:00 UTC, nadyaiva commented on src/index.html
> +				<h2 class="section__title">
Поняла. Спасибо за помощь. Запушила новый вариант.

2022-06-08 09:55 UTC, pankiale approved these changes

2022-06-08 09:56 UTC, pankiale approved these changes
please resolve conflicts before merge

2022-06-08 12:48 UTC, s-gusterev approved these changes

2022-06-08 12:52 UTC, merged