added footer desktop
pankiale/lyubimovka pull request #30
Opened 2022-06-08 16:10 UTC by RomanPestryakov98

2022-06-08 16:23 UTC, goalrazor commented
Подлить дев в index.css  - есть ошибки не найденного файла 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/48967745/172667320-df374945-7fb9-4f4b-aea3-18d2b5f8eaa5.png">

2022-06-08 16:31 UTC, goalrazor requested changes

2022-06-08 16:31 UTC, goalrazor commented on src/blocks/footer/footer.css
> +	font-family: 'Formular';
дописать альтернативный шрифт Arial, sans-serif

2022-06-08 16:31 UTC, goalrazor commented on src/blocks/footer/__location-title/footer__location-title.css
> +	font-family: 'Neue Machina';
дописать альтернативный шрифт Arial, sans-serif

2022-06-08 16:31 UTC, goalrazor commented on src/blocks/footer/__location-title/footer__location-title.css
> +	margin: 0;
NIT: два margina можно собрать в один 
margin: 0 0 16px;

2022-06-08 16:31 UTC, goalrazor commented on src/blocks/footer/__addres/footer__addres.css
> +.footer__addres {
NIT: typo в названии

2022-06-08 20:46 UTC, s-gusterev reviewed
![Снимок экрана от 2022-06-08 22-56-21](https://user-images.githubusercontent.com/83599219/172713806-ef1535df-923b-4f55-96a7-585ab942016f.png)

Ссылки в навигации надо немного поправить

2022-06-08 20:46 UTC, s-gusterev commented on src/blocks/footer/footer.css
> +.footer__logo {
Сейчас ссылка с логотипом растягивается на всю высоту и увеличивает зону кликабельности `align-self: start;` должно помочь

2022-06-08 20:46 UTC, s-gusterev commented on src/index.html
> +				<p>Политика конфиденциальности</p>
Политика конфиденциальности ссылка и внизу  - `shishki.collective `и `Яндекс.Практикума` или вся строка целиком

2022-06-08 20:46 UTC, s-gusterev commented on src/index.html
> +			<div class="footer__location">
Здесь подошел бы тег address

2022-06-08 20:46 UTC, s-gusterev commented on src/blocks/footer/footer.css
> +.footer__privacy-policy p {
по бэму не рекомендуется стилизировать селекторы тэгов

2022-06-10 12:15 UTC, s-gusterev approved these changes

2022-06-10 15:50 UTC, goalrazor commented on src/blocks/footer/footer.css
> +.footer__info img {
вот тут тоже img

2022-06-10 15:50 UTC, goalrazor commented on src/blocks/footer/footer.css
> +.partners-logo__logo:nth-of-type(1) img {
не надо стилизовать по тэгу

2022-06-10 15:51 UTC, goalrazor commented on src/blocks/footer/footer.css
> +.partners-logo__logo:nth-of-type(1) img {
и ниже там тоже самое

2022-06-10 17:22 UTC, goalrazor approved these changes

2022-06-11 09:48 UTC, pankiale requested changes
сломана секция performance

2022-06-11 10:47 UTC, closed without merging