Hotfix/slider
pankiale/lyubimovka pull request #49
Opened 2022-06-14 17:24 UTC by MarinaFominykh

В swiper.css дифференцирован селектор для слайдера с отзывами.

2022-06-15 07:35 UTC, goalrazor requested changes

2022-06-15 07:35 UTC, goalrazor commented on src/blocks/social-networks/social-networks.css
> +	background: contain no-repeat;
Тут неполное свойство background - нет самого контента или цвета

2022-06-15 07:35 UTC, goalrazor commented on src/blocks/swiper/swiper.css
> +		min-height: 361;
Почему без px?

2022-06-15 07:35 UTC, goalrazor commented on src/blocks/social-networks/social-networks.css
> +		margin-bottom: 24.78px;
значения с плавающей точкой могут по разному рендерится в разных браузерах, лучше их избегать. Думаю если тут будет 25px - будет норм

2022-06-15 08:42 UTC, MarinaFominykh commented on src/blocks/social-networks/social-networks.css
> +	background: contain no-repeat;
Убрала вообще, оно тут не нужно.

2022-06-15 08:42 UTC, MarinaFominykh commented on src/blocks/swiper/swiper.css
> +		min-height: 361;
Fixed.

2022-06-15 08:42 UTC, MarinaFominykh commented on src/blocks/social-networks/social-networks.css
> +		margin-bottom: 24.78px;
Fixed.

2022-06-15 09:09 UTC, goalrazor approved these changes

2022-06-16 16:56 UTC, nadyaiva approved these changes
работа проделана огромная! Я проблем не нашла)

2022-06-16 17:01 UTC, merged